#!/bin/bash

cd /etc/login.d/
mkdir -p /var/log/CAPESOS
echo "[`date +%m/%d-%H:%M:%S`] Lancement des scripts de login pour $USER">>/var/log/CAPESOS/login-script.log
for i in *
do
        if [ -x $i ]
        then
                echo "[`date +%m/%d-%H:%M:%S`] Execution de $i par $USER" >>/var/log/CAPESOS/login-script.log
                ./$i
        fi
done

