repository:
  description: CapesOS Repository
#  maintenance:
build:
  script:
    pre:
      #- echo "toto"
      #- "if [ ! -e /usr/bin/gradle ] ;then ln -s /usr/bin/gradle-* /usr/bin/gradle;fi"
      #- "[ ! -e /usr/bin/gradle ]&&ln -s /usr/bin/gradle-* /usr/bin/gradle"
#    post:
#        - etc-update --automode -3
  equo:
    package:
      install:
#        - dev-java/gradle-bin
        #- sci-libs/lapack-reference
#      remove:
#         - x11-themes/sabayon-artwork-isolinux	
#         - x11-themes/sabayon-artwork-grub	
  emerge:
    # Install each package separately
    split_install: 1
    jobs: 12
    webrsync: 0
    remove : 
        - app-misc/sabayon-skel
#    skip_sync: 0
    features: assume-digests binpkg-logs compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned -sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch usersandbox usersync xattr -userpriv
  overlays:
    - science
    - sage-on-gentoo
    - sabayon
    - sabayon-distro
  target:
    - sci-mathematics/scilab
    - sci-mathematics/geogebra
    - sci-mathematics/giac::sage-on-gentoo
    - app-doc/zeal::gentoo
    - x11-themes/capesos-artwork-wallpapers
    - x11-themes/capesos-artwork-core
    - x11-themes/capesos-artwork-grub
    - app-misc/capesos-skel
    - x11-themes/capesos-artwork-lightdm-slick-greeter
    - x11-themes/capesos-artwork-plymouth
    - x11-apps/capesos-screencapture
    - x11-misc/blackscreen
    - dev-python/notebook-capesos-icon
    - gnome-extra/gnome-calculator-capesos-icon
    - sci-mathematics/xcas-icon-capesos
    - dev-db/sqlitebrowser-icon-capesos
    - app-doc/zeal-icon-capesos
    - x11-themes/Humanity-Dark-Aqua-icon-theme
    - app-office/libreoffice-icon-capesos
    - app-doc/ressources-officielles-math
    - sci-calculators/Numworks
    - dev-python/Pyzo
    - sci-mathematics/scratch3-ac-grenoble
    - app-text/lecteur_pdf
    - net-analyzer/zabbix
    - app-doc/numpy-dash-docset
    - app-doc/matplotlib-dash-docset
    - app-doc/python2-dash-docset
    - app-doc/python3-dash-docset
    - app-doc/scipy-dash-docset
    - dev-python/imageio
    - app-admin/lsyncd
    - x11-themes/LightningBug-Dark-Blue
    - dev-lang/python

